### ISSUE TITLE
No convenient way to stop the mongodb-performance-test

### ISSUE THREAD

**Issue by 837278709** [idealo/mongodb-performance-test#1]
I mistakenly run the test jar package like this.
jre/bin/java \
-jar mongodb-performance-test.jar \
-m INSERT UPDATE_ONE \
-o 300000000000 \
-t 1000 1000\
-dropdb \
-h host \
-db PTDB \
-c TC1 &
Now I could not find a proper way to stop it other than reboot the system.
Could you please add a way to stop it or maybe lanch.sh and stop.sh.
Thanks. This project is awsome.

**Comment by kagahd** [comment]
Thank you for your feedback!
In order to stop the performance-test, you can simply kill the java process of the performance test. To kill **all** java processes you could type in a linux shell for example:`pkill java`
If you have other java processes running that you don't want to kill, look first for the right process-id like this in a linux shell: `ps aux | grep java | grep -v grep`
Then kill the related java process by using its process-id: `kill <pid>` 
But you're right, having a stop script would be still better.

**Comment by 837278709** [comment]
Thanks a lot for the answer and your attention. Great work!!!
